# Generated by Django 3.2.9 on 2021-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211120_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
